import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";
import { Container } from "@/components/Container";
import Footer from "@/components/Footer";
import { AuthProvider } from "@/contexts/auth-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export function Providers({ children }: { children: React.ReactNode }) {
  return <AuthProvider>{children}</AuthProvider>;
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="">
        <Providers>
          <header>
            <NavBar />
          </header>
          <Container>
            <main className="flex-1">{children}</main>
          </Container>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
